{{- if .Values.apiServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nudgebee-agent.fullname" . }}-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nudgebee-agent.fullname" . }}-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "nudgebee-agent.fullname" . }}-apiserver
  template:
    metadata:
      labels:
        app: {{ include "nudgebee-agent.fullname" . }}-apiserver
        nudgebeeComponent: "apiserver"
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- if or .Values.apiServer.annotations .Values.globalConfig.custom_annotations }}
        {{- if .Values.apiServer.annotations}} {{ toYaml .Values.apiServer.annotations | nindent 8 }}
        {{- end }}
        {{- if .Values.globalConfig.custom_annotations }} {{ toYaml .Values.globalConfig.custom_annotations | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "nudgebee-agent.fullname" . }}-runner-service-account
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      {{- include "nudgebee.runner.imagePullSecrets" (dict "root" . "config" .Values.apiServer) | nindent 6 }}
      containers:
      {{- include "nudgebee.runner.container" (dict "root" . "config" .Values.apiServer "containerName" "apiserver" "runnerMode" "FOREGROUND") | nindent 6 }}
      {{- include "nudgebee.runner.volumes" (dict "root" . "config" .Values.apiServer) | nindent 6 }}
      {{- if .Values.apiServer.nodeSelector }}
      nodeSelector: {{ toYaml .Values.apiServer.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.apiServer.affinity }}
      affinity: {{ toYaml .Values.apiServer.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.apiServer.tolerations }}
      tolerations: {{ toYaml .Values.apiServer.tolerations | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nudgebee-agent.fullname" . }}-apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nudgebee-agent.fullname" . }}-apiserver
    target: {{ include "nudgebee-agent.fullname" . }}-apiserver
spec:
  selector:
    app: {{ include "nudgebee-agent.fullname" . }}-apiserver
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
---
{{ if and (.Values.enableServiceMonitors) (or (.Values.enablePrometheusStack) (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nudgebee-agent.fullname" . }}-apiserver-service-monitor
  labels:
    release: {{ .Release.Name }}
spec:
  endpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels:
      app: {{ include "nudgebee-agent.fullname" . }}-apiserver
  targetLabels:
    - target
{{ end }}
{{- end }}